### ISSUE TITLE
SearchWP indexing fails for non-Hogan post types

### ISSUE THREAD

**Issue by stian-overasen** [DekodeInteraktiv/hogan-core#92]
For posts of post types that is not using Hogan modules we're still replacing the default content with module content when indexing.
```php
$post->post_content = $this->get_modules_content( $post );
```

This results in content not being indexed.

**Comment by stian-overasen** [comment]
Solution: Replace content with module content only if any modules is in use…?

```php
$module_content = $this->get_modules_content( $post );

if ( ! empty( $module_content ) ) {
  $post->post_content = $module_content;
}
```

**Comment by olethomas** [comment]
#win
